version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'secretpassword'
    # ports:
    #   - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/postgresql/data
  frontend:
    depends_on:
      - backend
    image: welbex-frontend
    build: ./welbex-frontend
    ports:
      - "8080:80"
  backend:
    depends_on:
      - db
    links:
      - db
    image: welbex-backend
    build: ./welbex-backend
    ports:
      - "3000:3000"
    environment:
      PGHOST: 'db'
      PGUSER: 'postgres'
      PGDATABASE: 'postgres'
      PGPASSWORD: 'secretpassword'
